absoluteurl: http://ICI3D.org
baseurl: ''
markdown: kramdown
exclude: ['index.html-OLD','people.md-OLD',redirect.html,README.md,run.sh,.wiki]
highlighter: rouge
gems:
  - jemoji
collections:
  profiles:
    output: true
    permalink: /people/:name
