absoluteurl: //www.ICI3D.org
url: //www.ICI3D.org
baseurl: ''
markdown: kramdown
exclude: ['index.html-OLD','people.md-OLD',redirect.html,README.md,run.sh,.wiki,template.md]
highlighter: rouge
year: 2023
theme: jekyll-theme-ici3d
collections:
  team:
    output: true
    permalink: /people/:name
defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: profile
