absoluteurl: http://www.ICI3D.org
url: http://www.ICI3D.org
baseurl: ''
markdown: kramdown
exclude: ['index.html-OLD','people.md-OLD',redirect.html,README.md,run.sh,.wiki,template.md]
highlighter: rouge
year: 2018
gems:
  - jemoji
collections:
  profiles:
    output: true
    permalink: /people/:name
defaults:
  - scope:
      path: ""
      type: profiles
    values:
      layout: profile
